title: RaDialog
description: This is a website for my awesome project.
baseurl: "/RaDialog" # the name of your GitHub repository
url: "https://chantalmp.github.io" # your GitHub Pages URL
theme: minima